export const actions = {
    RECEIVING: {
        NEW_MESSAGE: 'NEW_MESSAGE',
        UNREAD_MESSAGE_COUNT: 'UNREAD_MESSAGE_COUNT'
    },
    SENDING: {
        NEW_MESSAGE: 'NEW_MESSAGE',
        UNREAD_MESSAGE_COUNT: 'UNREAD_MESSAGE_COUNT'
    }
};
